apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-search-data
  labels:
    app: splunk
    role: splunk_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-search-config
  labels:
    app: splunk
    role: splunk_search_head
    tier: search
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 32Gi

