apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: splunk
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: splunk
    role: splunk_cluster_master
    tier: management 
spec:
  type: LoadBalancer
  selector:
    app: splunk
    role: splunk_cluster_master
    tier: management
  ports:
    - name: splunkweb
      port: 8000 
      targetPort: 8000
