apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: splunk
data:
  nginx-static.conf: |
    server {

      listen 80;

      location / {
        root /data/www;
        autoindex on;
      }
    }
